version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: market_prototype
    ports:
    -  5432:5432
    volumes:
    - ./data:/var/lib/postgresql/data

  server:
    build: .
    environment:
      PORT: 6540
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: market_prototype
      DATABASE_HOST: db
      DATABASE_DIALECT: postgres
    ports:
    - 6540:6540
    depends_on:
      - db
    command: bash -c "./wait-for-it.sh db:5432 && yarn migrate:up && yarn start"
